### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [spockNinja/linter-scspell#1]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`1.1.1`) of this package:
1. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: `json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] }`
2. Use a config schema instead. See the configuration section of https://atom.io/docs/latest/hacking-atom-package-word-count and https://atom.io/docs/api/latest/Config for more details
3. Config::unobserve no longer does anything. Call `.dispose()` on the object returned by Config::observe instead.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by spockNinja** [comment]
Thanks, @benogle. Should be cleaned up and ready for tomorrow.
