### ISSUE TITLE
Install `linter` automatically.

### ISSUE THREAD

**Issue by keplersj** [spockNinja/linter-scspell#2]
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

**Comment by keplersj** [comment]
Closing due to package not being actively developed.

**Comment by spockNinja** [comment]
This is a great idea. Sorry I missed this when it was suggested initially.

**Comment by spockNinja** [comment]
Closed by e0211b08d66b4e05c55039a8e9aa835102fdf255
